config/routes.rb
Rails.application.routes.draw do
  resources :likes, only: [:create, :destroy]
  resources :destinations
  resources :users, only: [:show, :new, :create, :edit, :update, :destroy]

  root 'application#index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :destinations do
    resources :likes
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord
  has_many :likes
  has_many :users, through: :likes

  def self.id_array
    @destinations = self.all
    @id_array = @destinations.map { |d| d.id }
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :destination
end

app/models/user.rb
class User < ApplicationRecord
  has_many :likes
  has_many :destinations, through: :likes

  validates :first_name, presence: true, length: (2..20)
  validates :last_name, presence: true, length: (2..20)
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length: (6..20)
  has_secure_password

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def authenticate(plain_text)
    BCrypt::Password.new(self.password_digest) == plain_text
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :logged_in?
  before_action :session_user_reset

  def session_user_reset
    # prevent the nav bar from breaking when there's no user in the database
    if User.all.count == 0
      session.delete(:user_id)
    end
  end

  def index
    if @user
      @user = User.find(session[:user_id])
      log_in(session[:user_id])
      @destination_sample = Destination.all.sample
    end
  end


  private

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.destroy(:user_id)
  end

  def logged_in?
    !!session[:user_id]
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  def show
    @destination = Destination.find(params[:id])
    @destination_sample = Destination.id_array.shuffle.first
    if !session[:user_id].nil?
      @user = User.find(session[:user_id])
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_like, only: [:destroy]
  before_action :require_user

  def create
    @destination = Destination.find(params[:destination_id])
    if already_liked?
      flash[:notice] = "You can't like more than once!"
      redirect_to destination_path(@destination)
    else
      @destination.likes.create(user_id: session[:user_id])
      flash[:notice] = "You have successfully added this destination!"
      redirect_to user_path(session[:user_id])
    end
  end

 def destroy
   # @destination = Destination.find(params[:id])
   if !(already_liked?)
     flash[:notice] = "Cannot unlike"
   else
     @like.destroy
     flash[:notice] = "You have successfully removed a liked place!"
   end
   redirect_to user_path(session[:user_id])
 end

  private

  def already_liked?
    Like.where(user_id: session[:user_id], destination_id: params[:destination_id]).exists?
  end

  def find_like
    @destination = Destination.find(params[:destination_id])
    @like = @destination.likes.find(params[:id])
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @destination_sample = Destination.all.sample
    if !session.empty?
      session.clear
    end
  end

  def create
    @destination_sample = Destination.all.shuffle.first
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
     log_in(@user)
     flash[:success] = "#{@user.first_name} has successfully logged in"
     redirect_to destination_path(@destination_sample)
    else
     flash.now[:danger] = "Invalid email or password"
     render 'new'
    end
  end

  def destroy
   session[:user_id] = nil
   flash[:success] = "You have logged out"
   redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(session[:user_id])

    if params[:like]
      @likes = @user.likes
    end
  end

  def new
    @user = User.new
  end

  def create
    @destination = Destination.find(1)
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      log_in(@user)
      redirect_to destination_path(@destination)
    else
      render :new
    end
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/index.html.erb
<div class="overlay"></div>
<div class="container slider-top-text">
    <div class="row">
        <div class="col-md-12 text-center">
            <p class="title" >Runaway</p>
            <p class="small_title">where should I runaway?</p>
            <div class="tell-me-button">
              <a class="btn btn-danger" href="<%= destination_path(Destination.all.sample.id) %>">&nbsp tell me →</a>
            </div>
        </div>
    </div>
</div>

app/views/destinations/show.html.erb
<div class="destination-container">
    <div class="destination-text">
      <h1 class="destination-name"> DO YOU WANT TO RUNAWAY TO </h1>
      <br>
      <h1 class="city-text"><%= @destination.name %>?<h1>
      <a class="btn btn-outline-secondary" href="#content" role="button">Hell yeah!</a>
      <a class="btn btn-outline-secondary" href="<%= destination_path("#{@destination_sample}") %>" role="button">Nah</a>
  </div>
</div>

<div id="city-container">
    <h1 id="content" class="city-name"> ~ <%= @destination.name %> ~ </h1>
    <% if @destination.img_url != nil %>
      <%= image_tag(@destination.img_url) %>
    <% end %>
    <br>
    <br>
    <br>
    <h2 class="whats-good">What's so great about <%= @destination.name %>?</h2>
    <br>

    <p class="city-content">
    <%= @destination.description %>
    </p>
    <p class="city-content"> <%= @destination.activity %></p>
    <p class="city-content"> <strong>Climate:</strong> <%= @destination.climate %> </p>
    <p class="city-content"> <strong>Estimated budget: $</strong><%= @destination.budget %></p>
    <center>
      <div id="like-button">
        <%= button_to '❤️ Add to Likes', destination_likes_path(@destination), method: :post %>
        <% @destination.likes.count %> <% (@destination.likes.count) == 1||0 ? 'Likes' : 'Likes'%>
        <% pre_like = @destination.likes.find { |like| like.user_id == session[:user_id]} %>
        <% if pre_like %>
        <%= button_to ' 💔 Remove from Likes ', destination_like_path(@destination, pre_like), method: :delete %>
        <% end %>
      </div>
    </center>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RunawayEurope</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Anton%7CFjalla+One"
    rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <header class="masthead">
  <body>
    <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
    <% end %>

    <%= render '../views/header' %>

    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>
</header>

app/views/users/_form.html.erb
<center>
<%= form_for(user, :html => {class: "form-horizontal", role: "form"}) do |f| %>

<div class="form-group">
  <div class="col-sm-4">
    <%= f.text_field :first_name, class: "form-control", placeholder: "First Name", autofocus: true %>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-4">
    <%= f.text_field :last_name, class: "form-control", placeholder: "Last Name", autofocus: true %>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-4">
    <%= f.email_field :email, class: "form-control", placeholder: "Email", autofocus: true %>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-4">
    <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-4">
    <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password Confirmation" %>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit "Create Account", class: 'btn btn-dark' %>
  </div>
</div>

<% end %>
</center>

app/views/users/edit.html.erb
<center>
<h1>Update Account</h1>
<% if @user.errors.any? %>
<div>
  <% @user.errors.full_messages.each do |msg| %>
  <%= msg %>
</div>
<% end %>
<% end %>
<%= render partial: "users/form", locals: {user: @user} %>
</center>

app/views/users/new.html.erb
<h1 align="center">Become a Runaway</h1>

<center>
  <% if @user.errors.any? %>
  <div class="container" >
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <div class="col-sm-5 alert alert-danger" role="alert">
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
              <li align="left"><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>

<!-- <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>

<div class="form-group">
  <div class="col-sm-4">
    <%= f.text_field :first_name, class: "form-control", placeholder: "First Name", autofocus: true %>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-4">
    <%= f.text_field :last_name, class: "form-control", placeholder: "Last Name", autofocus: true %>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-4">
    <%= f.email_field :email, class: "form-control", placeholder: "Email", autofocus: true %>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-4">
    <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-4">
    <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password Confirmation" %>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit "Create Account", class: 'btn btn-dark' %>
  </div>
</div>

<% end %>
</center> -->
<%= render partial: "users/form", locals: {user: @user} %>

app/views/users/show.html.erb
<%# user info %>
<div class="greet-user">
<h1>Hello <%= @user.first_name %>!</h1>
<%# destination that the user liked %>
<p>Your next destination is </p>
</div>
<div class="grid-container">
  <% @user.destinations.each do |d| %>
  <div class="grid-item">
    <a href="<%= destination_path(d) %>#content">
    <%= image_tag(d.img_url) %>
    </a>
    <h3><a href="<%= destination_path(d) %>#content"><%= d.name %></a></h3>
  </div>
  <% end %>
</div>


  <%= button_to "Edit Profile", edit_user_path, method: "get", class: "btn btn-dark" %>